onboarding = false

[keys]
prefix = "ctrl+a"
new_workspace = "prefix+n"
rename_workspace = "prefix+shift+n"
close_workspace = "prefix+shift+d"
new_tab = "prefix+t"
rename_tab = "prefix+shift+t"
close_tab = "prefix+shift+w"
next_tab = "ctrl+tab"
previous_tab = "ctrl+shift+tab"
next_workspace = "ctrl+alt+tab"
previous_workspace = "ctrl+alt+shift+tab"

[ui]
show_agent_labels_on_pane_borders = true
copy_on_select = false
prompt_new_tab_name = true

[keys.indexed]
workspaces = "ctrl+shift"
tabs = "alt"
