add_newline = false
command_timeout = 1000
format = "$hostname${custom.jj}$directory $character"

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"
vicmd_symbol = "[N](mauve) [➜](green)"

[directory]
style = "blue"
truncation_length = 4
truncate_to_repo = true

[git_branch]
disabled = true

[git_status]
disabled = true

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "green bold"
