[[links]]
src = "callisto/"
dst = "~/.config/hypr"
hosts = ["callisto"]

[[links]]
src = "parallels/input.lua"
dst = "~/.config/hypr/input.lua"
hosts = ["rheavm"]

[[links]]
src = "parallels/xkb/parallels.xkb"
dst = "~/.config/hypr/xkb/parallels.xkb"
hosts = ["rheavm"]
