[[dirs]]
path = "~/.gnupg"
mode = "0700"

[[links]]
src = "gpg.conf"
dst = "~/.gnupg/gpg.conf"

[[links]]
src = "gpg-agent.mac"
dst = "~/.gnupg/gpg-agent.conf"
os = "darwin"

[[links]]
src = "gpg-agent.linux"
dst = "~/.gnupg/gpg-agent.conf"
os = "linux"

[[links]]
src = "scdaemon.conf"
dst = "~/.gnupg/scdaemon.conf"
optional = true
