[[links]]
src = "settings.json"
dst = "~/.pi/agent/settings.json"

[[links]]
src = "settings-work.json"
dst = "~/.pi/agent/settings.json"
hosts = ["rselbach-KJG3M7PY7D"]

[[links]]
src = "models.json"
dst = "~/.pi/agent/models.json"

[[links]]
src = "extensions/common/*"
dst = "~/.pi/agent/extensions/<name>"

[[links]]
src = "extensions/hosts/rselbach-KJG3M7PY7D/*"
dst = "~/.pi/agent/extensions/<name>"
hosts = ["rselbach-KJG3M7PY7D"]

[[watch]]
path = "~/.pi/agent/extensions"

[[links]]
src = "../agents/AGENTS.md"
dst = "~/.pi/agent/AGENTS.md"

[[links]]
src = "agents"
dst = "~/.pi/agent/agents"

[[links]]
src = "prompts"
dst = "~/.pi/agent/prompts"
