-- Generated by nwg-displays on 2026-08-21 at 17:31:52. Do not edit manually.

hl.monitor({
    output = "Virtual-1",
    mode = "2560x1440@60.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "Virtual-2",
    mode = "1728x1084@59.95",
    position = "832x1440",
    scale = 1.0
})
hl.monitor({
    output = "Virtual-3",
    mode = "2560x1440@59.97",
    position = "2560x90",
    scale = 1.0
})
