// tty7 agent-hook opencode bridge — generated by tty7, do not edit.
// Bridges OpenCode plugin events onto `tty7 agent-hook opencode <event>`,
// which is inert outside tty7 (gated on the TTY7 env var).
// Loads on OpenCode 1.x (default `{ id, server }`) and 2.x (`{ id, setup }`).
import { spawn } from "node:child_process"

const EXE = "/Applications/tty7.app/Contents/MacOS/tty7-app"

// Spawned directly, not through a shell: there is no `sh` on Windows.
function run(event, sessionId) {
  return new Promise((resolve) => {
    try {
      const payload = sessionId ? JSON.stringify({ session_id: sessionId }) : ""
      const child = spawn(EXE, ["agent-hook", "opencode", event], {
        stdio: [payload ? "pipe" : "ignore", "ignore", "ignore"],
        windowsHide: true,
      })
      child.on("error", () => resolve())
      child.on("close", () => resolve())
      if (payload) {
        child.stdin.on("error", () => {})
        child.stdin.end(payload)
      }
    } catch {
      resolve()
    }
  })
}

// One pane's view of the event stream, shared by both plugin APIs.
function presence() {
  let sessionId = ""
  let announced = ""
  // A subagent runs in a child session on the *same* event stream, and its
  // status events are indistinguishable from the pane's own — only session
  // creation names a parent. Remember the children, so a task tool cannot
  // hand the pane the wrong session to resume, nor call the pane done when
  // only the subagent is.
  const children = new Set()
  // Every event carries the session id, so a pane that restarts can resume
  // the same session with `opencode --session`.
  const emit = (event) => run(event, sessionId)
  // The session id is only known once opencode creates the session; the
  // session-start report rides on the first event that names one, so a
  // restored pane can reattach to it.
  const capture = async (id) => {
    if (id && !children.has(id)) sessionId = id
    if (sessionId && sessionId !== announced) {
      announced = sessionId
      await emit("session-start")
    }
  }
  const ACTION = {
    "session.status.busy": "prompt-submit",
    "session.status.idle": "stop",
    "session.idle": "stop",
    "permission.asked": "permission-request",
    "permission.replied": "prompt-submit",
  }
  // `fields` is 1.x's `event.properties` or 2.x's `event.data`.
  const observe = async (type, fields) => {
    const info = fields.info
    // 1.x: `session.created`/`session.updated` carry the whole session.
    if (info?.id && info.parentID) children.add(info.id)
    // 2.x: `session.created` names the session and its parent directly.
    if (type === "session.created" && fields.sessionID && fields.parentID) children.add(fields.sessionID)
    if (fields.sessionID && children.has(fields.sessionID)) return
    await capture(fields.sessionID)
    const key = type === "session.status" ? `session.status.${fields.status?.type}` : type
    const action = ACTION[key]
    if (action) await emit(action)
  }
  return { emit, capture, observe }
}

// OpenCode 1.x: a factory returning hooks, run in the TUI's own process.
const server = async () => {
  if (!process.env["TTY7"]) return {}
  const pane = presence()
  return {
    dispose: async () => {
      await pane.emit("session-end")
    },
    "tool.execute.before": async (input) => {
      await pane.capture(input?.sessionID)
      await pane.emit("prompt-submit")
    },
    "permission.ask": async (input) => {
      await pane.capture(input?.sessionID)
      await pane.emit("permission-request")
    },
    event: async ({ event }) => {
      await pane.observe(event.type, event.properties ?? {})
    },
  }
}

// OpenCode 2.x: `setup` subscribes to the event stream and returns cleanup.
const setup = async (ctx) => {
  if (!process.env["TTY7"]) return
  // By default 2.x runs plugins in one background service shared by every
  // opencode on the machine: its sessions are not this pane's, and the
  // emitter it spawns has no way back to the pane's terminal. Only a server
  // the TUI started for itself (`--standalone`, or `opencode serve` run in
  // the pane) belongs to one pane.
  if (process.argv.includes("--service")) return
  if (typeof ctx?.event?.subscribe !== "function") return
  const pane = presence()
  const abort = new AbortController()
  // Not awaited: setup has to return for the plugin to finish loading.
  ;(async () => {
    try {
      for await (const event of ctx.event.subscribe({ signal: abort.signal })) {
        if (event?.type) await pane.observe(event.type, event.data ?? {})
      }
    } catch {}
  })()
  return async () => {
    abort.abort()
    await pane.emit("session-end")
  }
}

export const Tty7Presence = server

export default { id: "tty7", server, setup }
