// tty7 agent-hook opencode bridge — generated by tty7, do not edit.
// Bridges OpenCode plugin events onto `tty7 agent-hook opencode <event>`,
// which is inert outside tty7 (gated on the TTY7 env var).
export const Tty7Presence = async ({ $ }) => {
  if (!process.env["TTY7"]) return {}
  const cmd = "\"/Applications/tty7.app/Contents/MacOS/tty7-app\" agent-hook opencode "
  let sessionId = ""
  let announced = ""
  // A subagent runs in a child session on the *same* event stream, and its
  // status events are indistinguishable from the pane's own — only
  // `session.created`/`session.updated` name a parent. Remember the children,
  // so a task tool cannot hand the pane the wrong session to resume, nor call
  // the pane done when only the subagent is.
  const children = new Set()
  const emit = (event) => {
    // Every event carries the session id (`properties.sessionID`), so a pane
    // that restarts can resume the same session with `opencode --session`.
    const payload = sessionId ? new Response(JSON.stringify({ session_id: sessionId })) : undefined
    const proc = payload ? $`sh -c ${cmd + event} < ${payload}` : $`sh -c ${cmd + event}`
    return proc.quiet().nothrow()
  }
  // The session id is only known once opencode creates the session (the
  // `session.created` event); the session-start report rides on the first
  // event that names one, so a restored pane can reattach to it.
  const capture = async (id) => {
    if (id && !children.has(id)) sessionId = id
    if (sessionId && sessionId !== announced) {
      announced = sessionId
      await emit("session-start")
    }
  }
  const ACTION = {
    "session.status.busy": "prompt-submit",
    "session.status.idle": "stop",
    "session.idle": "stop",
    "permission.replied": "prompt-submit",
  }

  return {
    dispose: async () => {
      await emit("session-end")
    },
    "tool.execute.before": async (input) => {
      await capture(input?.sessionID)
      await emit("prompt-submit")
    },
    "permission.ask": async (input) => {
      await capture(input?.sessionID)
      await emit("permission-request")
    },
    event: async ({ event }) => {
      const properties = event.properties ?? {}
      const info = properties.info
      if (info?.id && info.parentID) children.add(info.id)
      if (properties.sessionID && children.has(properties.sessionID)) return
      await capture(properties.sessionID)
      const key = event.type === "session.status" ? `session.status.${properties.status?.type}` : event.type
      const action = ACTION[key]
      if (action) await emit(action)
    },
  }
}
